env:
  browser: true

settings:
  react:
    version: 'detect'

parserOptions:
  project:
    - ./tsconfig.json

extends:
  - ../.eslintrc.yml

overrides:
  - files:
      - vite.config.ts
    rules:
      import/no-default-export:
        - off
