version: '3'

services:
  dat-postgres:
    container_name: dat-postgres
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dataharbor
      POSTGRES_USER: student
      POSTGRES_PASSWORD: password
    restart: on-failure:3
    networks:
      - db_network

  dat-pgadmin:
    container_name: dat-pgadmin
    image: dpage/pgadmin4:latest
    restart: on-failure:3
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
