env:
  node: true

parserOptions:
  project:
    - ./tsconfig.json

extends:
  - ../.eslintrc.yml

overrides:
  - files:
    - 'src/libs/packages/database/libs/templates/migration.template.ts'
    rules:
      '@typescript-eslint/no-unused-vars': off
